version: '3'

services:
  reservation_server:       
    build:
      context: .
      dockerfile: Dockerfile.server
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "1"

  python_client:        
    network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - reservation_server
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "1"
